sudo: required
language: go
go:
  - 1.13.x
  - 1.14.x
  - master

env:
  - GO111MODULE=on
services:
  - docker
before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0
before_install:
  - docker-compose --version
  - docker-compose up -d
script:
  - make lint
  - make unittest
  - make benchtest
  - make build
  - make systest
after_success:
  - bash < (curl -s https://codecov.io/bash)
